import test from 'node:test';
import assert from 'node:assert/strict';
import { Group } from '../src/worker.js';
import { linkLegacyIdentity } from '../src/access.js';
test('vincula el navegador previo con la cuenta autenticada sin perder permisos ni planes',()=>{
 const legacy=crypto.randomUUID(), account=crypto.randomUUID();
 const group={owner:legacy,admins:[legacy],members:[{id:'member',token:legacy,name:'Ana',version:1}],banned:[],events:[{creatorToken:legacy,participants:[{token:legacy,name:'Ana'}],comments:[{token:legacy,name:'Ana'}]}]};
 assert.equal(linkLegacyIdentity(group,legacy,account),true);
 assert.equal(group.owner,account); assert.deepEqual(group.admins,[account]); assert.equal(group.members[0].token,account); assert.equal(group.events[0].creatorToken,account); assert.equal(group.events[0].participants[0].token,account); assert.equal(group.events[0].comments[0].token,account);
});
test('migra el grupo existente, protege datos, administra permisos y revoca contraseñas', async () => {
 const owner=crypto.randomUUID(), guest=crypto.randomUUID(), stranger=crypto.randomUUID();
 const map=new Map([['group',{name:'Grupo existente',owner,events:[]}]]);
 const instance=new Group({storage:{get:async k=>structuredClone(map.get(k)),put:async(k,v)=>map.set(k,structuredClone(v)),delete:async k=>map.delete(k),deleteAll:async()=>map.clear()},blockConcurrencyWhile:fn=>fn()});
 async function req(token,path='',method='GET',body){const r=await instance.fetch(new Request('https://example.com/api/groups/'+crypto.randomUUID()+path,{method,headers:{'X-Participant':token},...(body?{body:JSON.stringify(body)}:{})}));return {status:r.status,data:await r.json()};}
 assert.equal((await req(owner)).data.owner,true);
 assert.equal((await req(guest,'/settings','PATCH',{name:'Ataque'})).status,403);
 assert.equal((await req(owner,'/settings','PATCH',{name:'Amigos',password:'Clave inicial 123'})).status,200);
 const denied=await req(stranger);assert.equal(denied.status,401);assert.equal(denied.data.name,undefined);assert.equal(denied.data.members,undefined);
 assert.equal((await req(guest,'/unlock','POST',{name:'Bea',password:'Incorrecta'})).status,401);
 const unlocked=await req(guest,'/unlock','POST',{name:'Bea',password:'Clave inicial 123'});
 assert.equal(unlocked.status,200);assert.equal(unlocked.data.members.length,2);assert.equal(JSON.stringify(unlocked.data).includes(owner),false);
 const member=unlocked.data.members.find(m=>m.mine);
 assert.equal((await req(guest,'/admins','PATCH',{memberId:member.id,admin:true})).status,403);
 const guestPlan=await req(guest,'/events','POST',{title:'Plan de Bea',place:'Centro',capacity:1,date:'2099-01-01'});
 assert.equal(guestPlan.status,200);assert.equal(guestPlan.data.events[0].title,'Plan de Bea');
 assert.equal((await req(guest,`/events/${guestPlan.data.events[0].id}`,'PATCH',{title:'Plan editado',place:'Centro',capacity:2,date:'2099-01-02'})).data.events[0].title,'Plan editado');
 assert.equal((await req(stranger,`/events/${guestPlan.data.events[0].id}`,'PATCH',{title:'Ataque',place:'Centro',capacity:2,date:'2099-01-02'})).status,401);
 assert.equal((await req(guest,`/events/${guestPlan.data.events[0].id}`,'DELETE')).status,200);
 assert.equal((await req(owner,'/admins','PATCH',{memberId:member.id,admin:true})).status,200);
 assert.equal((await req(guest,'/settings','PATCH',{name:'Nuevo nombre',password:'Nueva clave 456'})).status,200);
 assert.equal((await req(owner,'/admins','PATCH',{memberId:member.id,admin:false})).status,200);
 assert.equal((await req(guest)).status,401);
 assert.equal((await req(guest,'/unlock','POST',{name:'Bea',password:'Clave inicial 123'})).status,401);
 assert.equal((await req(guest,'/unlock','POST',{name:'Bea',password:'Nueva clave 456'})).status,200);
 const mine=(await req(owner)).data.members.find(m=>m.mine);
 assert.equal((await req(owner,'/admins','PATCH',{memberId:mine.id,admin:false})).status,400);
 assert.equal(map.get('group').events.length,0);
 assert.equal(map.get('group').password.hash.includes('Nueva clave'),false);
 const event=(await req(owner,'/events','POST',{title:'Cena',place:'Centro',capacity:1,date:'2099-01-01'})).data.events.at(-1);
 await req(guest,`/events/${event.id}/participants`,'POST',{name:'Bea'});
 await req(owner,`/events/${event.id}/participants`,'POST',{name:'Ana'});
 assert.equal((await req(guest,'/status','PATCH',{closed:true})).status,403);
 assert.equal((await req(owner,'/status','PATCH',{closed:true})).data.closed,true);
 assert.equal((await req(stranger,'/unlock','POST',{name:'Otro',password:'Nueva clave 456'})).status,401);
 assert.equal((await req(guest,`/events/${event.id}/participants`,'POST',{name:'Bea'})).status,400);
 assert.equal((await req(guest)).status,200);
 assert.equal((await req(owner,'/status','PATCH',{closed:false})).data.closed,false);
 assert.equal((await req(guest,`/members/${mine.id}`,'DELETE')).status,403);
 assert.equal((await req(owner,`/members/${mine.id}`,'DELETE')).status,400);
 const expelled=await req(owner,`/members/${member.id}`,'DELETE');
 assert.equal(expelled.status,200);
 const remainingEvent=expelled.data.events.find(item=>item.title==='Cena');
 assert.equal(remainingEvent.participants.length,1);
 assert.equal(remainingEvent.participants[0].waiting,false);
 assert.equal((await req(guest)).status,401);
 assert.equal((await req(guest,'/unlock','POST',{name:'Bea',password:'Nueva clave 456'})).status,401);
 assert.equal((await req(owner,'/settings','PATCH',{name:'Sin contraseña',password:''})).data.protected,false);
 assert.equal((await req(stranger)).status,200);
 assert.equal((await req(stranger,'','DELETE',{confirmName:'Sin contraseña'})).status,403);
 assert.equal((await req(owner,'','DELETE',{confirmName:'Nombre incorrecto'})).status,400);
 assert.equal((await req(owner,'','DELETE',{confirmName:'Sin contraseña'})).data.deleted,true);
 assert.equal(map.has('group'),false);
 assert.equal((await req(owner)).status,410);
 assert.equal((await req(owner,'','POST',{name:'Recrear'})).status,410);
});
